### ISSUE TITLE
Checkbox form fields are not properly handled by API

### ISSUE THREAD

**Issue by roadster31** [thelia/thelia#1199]
When a form field is defined as a checkbox, the field value is always 1 in the API Controller, whatever the request parameters are.

Example for the visible field of a category : 
```
... snip ...
            ->add(
                'visible',
                'checkbox',
                [
                    'required' => false,
                    'label' => $this->translator->trans('This category is online')
                ]
            )
... snip ...
```

If we define category creation request parameters with visible = 0: 

```
[
    'title' => 'test en',
    'locale' => 'en_US',
    'visible' => 0,
    'parent' => 0
];
```

During the request processing, in  `CategoryController::getUpdateEvent()`, `$data['visible']` is 1 instead of 0.

If the `visible` field is defines as an `integer` instead of `checkbox`, everything is fine.

This issue prevent clean form definitions in front and back-office.

**Comment by bibich** [comment]
There is no other API forms that use checkbox field but we should keep in mind this issue. 
And this issue is fixed by PR #1200

**Comment by roadster31** [comment]
Well... If we "should keep in mind this issue" (which is not fixed, btw) , please don't close it.

**Comment by bibich** [comment]
Ok I don't close this issue. 
So we have to implement custom forms or override default forms especially for the API.
